apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: {{ .Values.image.repository }}
  config1.toml: |-
    {{- $arr := (regexSplit  "[\r\n]+" (.Files.Get "config1.toml") -1 )}}
    - {{  index $arr  0 }}
    - {{  index $arr  1 }}
    ###############################
    {{- range $outer := $arr }}
    {{- $inner := (regexSplit "=" $outer -1) }}
    {{- $key := index $inner 0 | trim }}
    {{- $value := index $inner 1 | trim }}
    - @@{{ $key }}={{ $value }}
    {{- end }}
    ###############################
  template: {{ .Template.Name }}
  templateBasePath: {{ .Template.BasePath }}
  KubeVersion : {{ .Capabilities.KubeVersion   }} 