apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: {{ .Values.image.repository }}
  config1.toml: |
    {{- $arr := (regexSplit  "[\r\n]+" (.Files.Get "config1.toml") -1 )}}
    - {{  index $arr  0 }}
    - {{  index $arr  1 }}
    {{- range $arr}}
    {{- range regexSplit "=" . -1 }}
    {{- end }}
    {{- $kv := regexSplit "=" . -1 }}
    - @@{{ index $kv 0  | trim}}={{index $kv 1  | trim}}
    {{- end}}
    
    
